# Change these first
owner: BrantLab # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: BrantLab
    url: https://brantlab.com
  - name: Convoy Fire & EMS
    url: https://convoyfireandems.com
  - name: Emergency Reporting
    url: https://emergencyreporting.com
  - name: Dispatch Recordings
    url: https://dispatch.brantlab.com
  - name: Secret Software
    url: $SECRET1
  - name: RAC
    url: https://rac.grunetworks.xyz
  - name: Convoy Daycare
    url: https://Convoydaycare.com
  - name: CFD WAN1
    check: "tcp-ping"
    url: wan1.convoyfireandems.com
    port: 443


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: upptime.brantlab.com
  # baseUrl: /your-repo-name
  logoUrl: https://authentik.brantlab.xyz/media/application-icons/logo_only.png
  name: BrantLab Upptime
  introTitle: "**BrantLab Upptime**"
  introMessage: "Various website status checked from an external source"
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

i18n:
  footer: " "
  
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 6 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "0 0 * * *"
